prefix = "n!"
langs = "en" # Avalabile ro / en / custom
token = "DISCORDTOKENGOSEHEREBABBY"
botactivity = "Play.YourNetWork.Com"
dscserver = "000000000000000000"
memberroleid = 000000000000000000
servername = "YourNetWork"
homelink = "https://your.network"
banslink = "https://bans.your.network"
forumlink = "https://forum.your.network"
votelink = "https://vote.your.network"
storelink = "https://store.your.network"
serverip = "play.your.network" # You can add the port to
enable2ndip = "true"
n2ip = "" # You can add the port to
enablelauncher = "true"
launcherlink = "https://launcher.your.network"